apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-barman
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: plugin-barman-cloud
      targetRevision: 0.7.1
      helm:
        valueFiles:
          - $values/argocd/apps/cloudnative-pg/barman/values.yaml
    - repoURL: https://github.com/washington1995luiz/presentation-cloudnativepg.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
