apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: app-postgres-backups
  namespace: cnpg
spec:
  configuration:
    destinationPath: s3://backup-database/cloudnativepg/app-postgres
    endpointURL: https://05740a57703ebe195c15dabbf102cc77.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: cnpg-r2-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-r2-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      encryption: AES256
      maxParallel: 2
    data:
      compression: gzip
      encryption: AES256
      jobs: 2
  retentionPolicy: 30d
  instanceSidecarConfiguration:
    logLevel: info
    retentionPolicyIntervalSeconds: 1800
