apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: app-postgres-pre-truncate
  namespace: cnpg
spec:
  cluster:
    name: app-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
